Better-Style-Dropdown-Menu
matooo3/Pencil2Pixel pull request #25
Opened 2024-05-03 18:36 UTC by matooo3

Resoves #24 
---
**Changes:**

1. Fixed the issue where the dropdown menu wouldn't close after selecting a style.
   - Added event listener to close the dropdown menu when a style is selected
   - Had to change some things from the css basic function, instead of using hover i used:
     - mouseenter and mouseleave, click to get better control and more convenient functionality

2. Prevented selecting the caption and buttons as text.
  - no user select

4. Prevent the appearance of a scrollbar when opening the style select dropdown.
   - no overflow.
---

2024-05-06 22:24 UTC, xSouperMan requested changes, later dismissed
Tested locally and found:

- If you hover over the styles button and click on it twice the styles appear when **not** hovering over the button and disappear when hovering over the button again
- Can't scroll down to the generated image

Other than that, it works fine.

2024-05-13 11:10 UTC, matooo3 commented
Thank you for your review!

> Tested locally and found:
> 
> * If you hover over the styles button and click on it twice the styles appear when **not** hovering over the button and disappear when hovering over the button again
=> Fixed

> * Can't scroll down to the generated image
=> removed the hidden overflow

2024-05-13 11:12 UTC, matooo3 commented
And creating new issue for the second problem, i just removed my wrong changes, but would still be nice if we find another way to fix the scrollbar thing.

2024-05-26 13:56 UTC, joru33 approved these changes

2024-05-26 13:57 UTC, merged